language: c
compiler: gcc
services: docker
before_install:
  - sudo apt-get update -q
  - export NPS_VERSION=`awk -f git-describe-remote-pgs.awk https://github.com/pagespeed/ngx_pagespeed  | grep -o "[0-9][^-]*" | head -n 1`
  - export NGINX_VERSION=`awk -f git-describe-remote-ngx.awk https://github.com/nginx/nginx  | grep -o "[0-9][^-]*" | head -n 1`
  - export LPNG_VERSION=1.2.56
  - export LPNG_LIB=libpng12
  - mkdir binginx
script: #ngx pgs
  - docker run -it -v ${PWD}/binginx:/home/binginx alpine sh /home/binginx/s.sh
before_deploy: 
  - cd
  - tar -czf nginx-${NGINX_VERSION}.tar.gz ${PWD}/binginx/nginx ${PWD}/binginx/libpng*
deploy:
  provider: releases
  api_key:
    secure: IjbTlcXeBfr6SqYc2tayT3vb9g3R063aKul7qyPgLDBIc62BxjwhfDYxEECUmeUnNZseLVyWypGkAJOFRfyMC/3HiY5WXBjXZ+cg7MJA7h1Avsn1cAR0RyrmnDu0u98M6hhUktM8w+vwSBqfSIgvjQ0avuMC2xYiwHJGauOpVStJ876WX9yLvJ1kUF7pf04G6IcXrOVkEkGCOPAjKWXXAcDrkLKLchbTKLgJF7RhgRCWu4TrWvSmwuzzuDDuzTr/oydQtqW2Fu2zXx2SfeiSNTAI8PIJS94IZV82/YKPxC//WvP6GicukdpIrQSSxzRVETrx1OwUihwuq9ONFwyTPjDXav+i/QaFUzCmwfkmh/lspsjvfvTM4ZrwMDrHVagKblYMlkID+wS1UOby9n3MqZkGjHa+uOY09puHqISAUgQlHzdLjKuBaw5HihIQMEiH6BJjQ+K3BQ5IY1OohC3u7idQNipLoaFrwn+BQ8P074mb3YeazXVZGMCVtJwUqt08dVdkc2Fe8CLrej4GdcnONXEHOS8yHE9Qsfgc2UeFtLU81phH9dXW7+niK6UtvDbXJzu8u7ATC0tCgSWG5JrkrBL96A8szMfrER2ksxJhoVtOyxf9YmkF6qDyH6ohvu+d41gCaR3jwhGOkG2toBU6VTu7DfiX1m1GZaeINXSQfu4=
  file: nginx-${NGINX_VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
